apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-ingress
  namespace: immich
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: haproxy
  tls:
  - hosts:
    - photos.hammers.no
    secretName: photos-hammers-no-tls
  rules:
  - host: photos.hammers.no
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: immich-external
            port:
              number: 80